export const seedData = {
  users: {
    _model: "User",
    bernard: {
      firstName: "Bernard",
      lastName: "Cattigan",
      email: "b.cattigan@placemark.ie",
      password: "secret123",
    },
    admin: {
      firstName: "Admin",
      lastName: "User",
      email: "admin@placemark.ie",
      password: "secret123",
    },
  },
  categories: {
    _model: "Category",
    category1: {
      name: "Weather Stations",
      filter: "Type of Weather Station",
      userId: "->users.bernard",
    },
    category2: {
      name: "Places I have visited in Ireland",
      filter: "Year visited",
      userId: "->users.bernard",
    },
  },
  placemarks: {
    _model: "Placemark",
    placemark1: {
      name: "Athenry",
      lat: 53.2892,
      lon: -8.7856,
      desc: "Athenry AWS is situated within the grounds of Teagasc, Athenry, Co Galway and was installed in 2010. Daily rainfall readings were taken at Athenry from 1944 to 1975",
      filter: "AWS",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark2: {
      name: "Ballyhaise",
      lat: 54.0514,
      lon: -7.3097,
      desc: "Ballyhaise AWS is situated within the grounds of Teagasc, Ballyhaise, Co Cavan and was installed in 2003. The station replaced a synoptic station which closed at Clones, Co Monaghan in 2008. A manual climate station taking daily measurements was situated within the college from 1932 to 2005",
      filter: "AWS",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark3: {
      name: "Belmullet",
      lat: 54.2275,
      lon: -10.0069,
      desc: "The station opened in September 1956. It replaced the station at Blacksod Lighthouse, 10 miles to the SW, which was run by the Sweeney family. It was from Blacksod that the observation, which finally determined the date of the D-Day landings in June 1944, emanated. The station is regarded as being particularly important because of its location on the western fringe of Europe. In 2012, the manual station was replaced by an AWS situated on the same site",
      filter: "AWS",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark4: {
      name: "Carlow Oakpark",
      lat: 52.8611,
      lon: -6.9153,
      filter: "AWS",
      desc: "Oak Park AWS is situated within the grounds of Teagasc, Oak Park, Co Carlow. The AWS was installed in 2003 and replaced a manual climate station which has taken daily readings since 1957",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark5: {
      name: "Claremorris",
      lat: 53.7108,
      lon: -8.9925,
      filter: "AWS",
      desc: "The station opened on the 9th November 1943 as a fully manned synoptic station. The manual station was replaced by an AGI automatic station in 1996. The station at Claremorris was officially closed on 1st November 2010 and was replaced by a TUCSON* Automatic Weather Station at the same location from January 1, 2010",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark6: {
      name: "Dunsany",
      lat: 53.5158,
      lon: -6.6600,
      filter: "AWS",
      desc: "The AWS is situated within the grounds of Teasgasc Grange, Boycetown, Co Meath. The present station was commissioned in 2006 replacing a manual climate station which was installed in 1963",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark7: {
      name: "Fermoy Moore Park",
      lat: 52.1639,
      lon: -8.2639,
      filter: "AWS",
      desc: "Moore Park AWS is situated within the grounds of Teagasc, Moore Park, Co Cork and was installed in 2003. The station replaced a manual station which was situated on the site since 1961",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark8: {
      name: "Finner",
      lat: 54.4939,
      lon: -8.2431,
      filter: "AWS",
      desc: "The current automatic weather station (AWS) was installed in Finner Army camp, Ballyshannon, Co. Donegal on the 1st November 2010. It replaced an existing AWS which had taken measurements since April 1996",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark9: {
      name: "Gurteen",
      lat: 53.0531,
      lon: -8.0086,
      filter: "AWS",
      desc: "Gurteen AWS was opened in the grounds of Gurteen Agricultural College, Co Tipperary in April 2008. The station was opened as a replacement to Birr Synoptic station which officially closed on the 1st January 2009",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark10: {
      name: "Johnstown Castle",
      lat: 52.2978,
      lon: -6.4967,
      filter: "AWS",
      desc: "Johnstown Castle AWS is situated within the grounds of Teagasc, Johnstown Castle, Co Wexford. An initial AWS was installed in 2003 and replaced a manual station which had taken daily measurements since 1914. Due to anthropogenic developments impacting on exposure the AWS was moved to a new location within the Teagasc grounds in 2009",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark11: {
      name: "Mace Head",
      lat: 53.3258,
      lon: -9.9008,
      filter: "AWS",
      desc: "The AWS at Mace Head is situated within the grounds of the NUI , Galway research centre near Carna, Co Galway. The station was installed in 2003",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark12: {
      name: "Malin Head",
      lat: 55.3719,
      lon: -7.3392,
      filter: "AWS",
      desc: "Malin Head synoptic weather station is situated at the most northerly point on the island of Ireland, at the top of the Inishowen peninsula in County Donegal. The nearest town is Carndonagh, which is 19 Km south southeast of the station",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark13: {
      name: "Markee",
      lat: 54.1750,
      lon: -8.4556,
      filter: "AWS",
      desc: "Markree Castle AWS is situated close to Markree Castle, Co Sligo.. The present station was commissioned in 2005 replacing a manual climate station which measured daily temperature and rainfall from 1860 to 1998. Due to site exposure, wind in not measured at the station",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark14: {
      name: "Mount Dillon",
      lat: 53.7269,
      lon: -7.9808,
      filter: "AWS",
      desc: "The AWS is situated on Bord Na Mona land north of Lanesborough. It was installed in September 2003",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark15: {
      name: "Mullingar",
      lat: 53.5372,
      lon: -7.3622,
      filter: "AWS",
      desc: "Mullingar AWS is situated to the west of Mullingar, Co. Westmeath. The station was automated in 1998",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark16: {
      name: "Newport",
      lat: 53.9222,
      lon: -9.5722,
      filter: "AWS",
      desc: "Newport (Furness) AWS is situated within the Marine Institute research centre to the North-West of Newport, Co Mayo. The station is positioned on an isthmus separating Lough Feegh (fresh water) and Furness Lough (salt water) .The present station was commissioned in January 2005 replacing a daily manual climate station which was installed in 1959",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark17: {
      name: "Phoenix Park",
      lat: 53.3636,
      lon: -6.3497,
      filter: "AWS",
      desc: "The Phoenix Park AWS is situated within the grounds of the Ordnance Survey of Ireland in the Phoenix Park, Dublin. The current station was installed in 2003 and replaced a manual climate which was established in 1829",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark18: {
      name: "Roches Point",
      lat: 51.7931,
      lon: -8.2444,
      filter: "AWS",
      desc: "Roches Point AWS is situated in the south eastern tip of Cork Harbour. The present station was commissioned in 2004 replacing an older AWS which was installed in 1991. Prior to this, Roches Point was a fully manned synoptic station measuring hourly data since 194",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark19: {
      name: "Sherkin Island",
      lat: 51.4764,
      lon: -9.4278,
      filter: "AWS",
      desc: "Sherkin Island AWS is situated within the grounds of the Sherkin Island Marine Station, Co Cork. The island is situated approximately 2 km off the west Cork village of Baltimore. The station is situated on north-west end of the island and was commissioned in 2004. A manual climate station measuring daily rainfall and temperature was installed in 1972 and remains open",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark20: {
      name: "Valentia",
      lat: 51.9383,
      lon: -10.2408,
      filter: "AWS",
      desc: "Valentia Observatory is part of Met Éireann, the Irish Meteorological Service. It is located one kilometre west of the town of Cahirciveen, on the estuary of the Feartha river",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark21: {
      name: "Abbeyfeale",
      lat: 52.3905,
      lon: -9.3078,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark22: {
      name: "Adare Manor",
      lat: 52.5532,
      lon: -8.7852,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark23: {
      name: "Ardara",
      lat: 54.7698,
      lon: -8.4202,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark24: {
      name: "Ardee",
      lat: 53.8537,
      lon: -6.5695,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark25: {
      name: "Arklow",
      lat: 52.8341,
      lon: -6.1305,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark26: {
      name: "Ashford",
      lat: 53.0250,
      lon: -6.0754,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark27: {
      name: "Ballinamore",
      lat: 54.0523,
      lon: -7.8266,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark28: {
      name: "Ballincurrig",
      lat: 52.0108,
      lon: -8.2005,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark29: {
      name: "Ballybunion",
      lat: 52.4903,
      lon: -9.6697,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark30: {
      name: "Ballycroy",
      lat: 54.0572,
      lon: -9.8425,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark31: {
      name: "Ballymore",
      lat: 53.9424,
      lon: -8.3269,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark32: {
      name: "Ballyshannon Cherrymount",
      lat: 54.4920,
      lon: -8.1540,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark33: {
      name: "Belderrig",
      lat: 54.3097,
      lon: -9.5681,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark34: {
      name: "Botanic Gardens Glasnevin",
      lat: 53.3701,
      lon: -6.2704,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark35: {
      name: "Bunclody",
      lat: 52.6446,
      lon: -6.6396,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark36: {
      name: "Cahore",
      lat: 52.5624,
      lon: -6.2094,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark37: {
      name: "Carron",
      lat: 53.0303,
      lon: -9.0775,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark38: {
      name: "Cashel",
      lat: 52.4587,
      lon: -7.8289,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark39: {
      name: "Castlerea",
      lat: 53.7570,
      lon: -8.4954,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark40: {
      name: "Clareville Limerick",
      lat: 52.7019,
      lon: -8.5286,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark41: {
      name: "Clonakilty",
      lat: 51.6308,
      lon: -8.8480,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark42: {
      name: "Clonmacnoise",
      lat: 53.3261,
      lon: -7.9868,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark43: {
      name: "Clonmel",
      lat: 52.3580,
      lon: -7.6748,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark44: {
      name: "Cloosh",
      lat: 53.3598,
      lon: -9.3398,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark45: {
      name: "Connemara National Park",
      lat: 53.5512,
      lon: -9.9421,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark46: {
      name: "Curragh",
      lat: 53.1691,
      lon: -6.8488,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark47: {
      name: "Derrybrien",
      lat: 53.0664,
      lon: -8.6003,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark48: {
      name: "Dingle",
      lat: 52.1350,
      lon: -10.2718,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark49: {
      name: "Dooks",
      lat: 52.0864,
      lon: -9.9281,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark50: {
      name: "Dundalk",
      lat: 54.0519,
      lon: -6.3514,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark51: {
      name: "Dungarvan",
      lat: 52.0807,
      lon: -7.5549,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark52: {
      name: "Dunmanway",
      lat: 51.7211,
      lon: -9.1003,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark53: {
      name: "Durrow",
      lat: 52.8479,
      lon: -7.3740,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark54: {
      name: "Edenderry (Ballinla)",
      lat: 53.3348,
      lon: -7.1454,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark55: {
      name: "Emyvale",
      lat: 54.3366,
      lon: -6.9558,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark56: {
      name: "Glengarriff",
      lat: 51.7367,
      lon: -9.5441,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark57: {
      name: "Glenveagh National Park",
      lat: 55.0510,
      lon: -7.9380,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark58: {
      name: "Gweedore Weir",
      lat: 55.0490,
      lon: -8.2303,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark59: {
      name: "Illies",
      lat: 55.1510,
      lon: -7.3480,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark60: {
      name: "Inagh Mount Callan",
      lat: 52.8417,
      lon: -9.2383,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark61: {
      name: "Inishcarra",
      lat: 51.9032,
      lon: -8.6691,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark62: {
      name: "John F Kennedy Arboretum",
      lat: 52.3176,
      lon: -6.9408,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark63: {
      name: "Kilcogy",
      lat: 53.8333,
      lon: -7.4231,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark64: {
      name: "Kilkit",
      lat: 54.0727,
      lon: -6.8851,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark65: {
      name: "Killarney",
      lat: 52.0220,
      lon: -9.5012,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark66: {
      name: "Limerick Junction",
      lat: 52.5079,
      lon: -8.2033,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark67: {
      name: "Lisglennon",
      lat: 54.1881,
      lon: -9.2275,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark68: {
      name: "Lough Easkey",
      lat: 54.2079,
      lon: -8.8670,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark69: {
      name: "Lough Mourne",
      lat: 54.7676,
      lon: -7.8651,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark70: {
      name: "Loughan House",
      lat: 54.2889,
      lon: -7.9166,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark71: {
      name: "Maam Valley",
      lat: 53.5369,
      lon: -9.6086,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark72: {
      name: "Mallow",
      lat: 52.1914,
      lon: -8.6495,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark73: {
      name: "Millstreet",
      lat: 52.0669,
      lon: -9.0585,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark74: {
      name: "Mount Russell",
      lat: 52.3301,
      lon: -8.5688,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark75: {
      name: "Mountbellew",
      lat: 53.4686,
      lon: -8.4934,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark76: {
      name: "Navan",
      lat: 53.6989,
      lon: -6.7157,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark77: {
      name: "Nealstown",
      lat: 52.9928,
      lon: -7.7042,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark78: {
      name: "Piltown",
      lat: 52.3523,
      lon: -7.3131,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark79: {
      name: "Portlaoise",
      lat: 53.0454,
      lon: -7.3074,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark80: {
      name: "Raphoe (Tops)",
      lat: 54.8496,
      lon: -7.5991,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark81: {
      name: "Roscommon",
      lat: 53.6168,
      lon: -8.1902,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark82: {
      name: "Shanganagh Dublin",
      lat: 53.2451,
      lon: -6.1153,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark83: {
      name: "Sligo Airport",
      lat: 54.2795,
      lon: -8.5989,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark84: {
      name: "Springfield Castle",
      lat: 52.3525,
      lon: -8.9536,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark85: {
      name: "Straide",
      lat: 53.9250,
      lon: -9.1264,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark86: {
      name: "Terryland",
      lat: 53.2853,
      lon: -9.0543,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark87: {
      name: "Thomastown",
      lat: 52.5248,
      lon: -7.1905,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark88: {
      name: "Thurles",
      lat: 52.6892,
      lon: -7.8351,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark89: {
      name: "Tourmakeady",
      lat: 53.6814,
      lon: -9.3722,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark90: {
      name: "Tuam",
      lat: 53.5161,
      lon: -8.8808,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark91: {
      name: "Tulla Clare",
      lat: 52.8561,
      lon: -8.7569,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark92: {
      name: "Waterford City",
      lat: 52.2542,
      lon: -7.1314,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark93: {
      name: "Wexford Wildfowl Reserve",
      lat: 52.3573,
      lon: -6.4206,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark94: {
      name: "Youghal",
      lat: 51.9647,
      lon: -7.8565,
      filter: "ACS",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark95: {
      name: "Ballypatrick Forest",
      lat: 55.1810,
      lon: -6.1530,
      filter: "NI",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark96: {
      name: "Belfast International Airport",
      lat: 54.6640,
      lon: -6.2240,
      filter: "NI",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark97: {
      name: "Castlederg",
      lat: 54.7070,
      lon: -7.5770,
      filter: "NI",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark98: {
      name: "Glenanne",
      lat: 54.2370,
      lon: -6.5020,
      filter: "NI",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark99: {
      name: "Lough Fea",
      lat: 54.7210,
      lon: -6.8140,
      filter: "NI",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark100: {
      name: "Magilligan",
      lat: 55.1604,
      lon: -6.9492,
      filter: "NI",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark101: {
      name: "Casement Aerodrome",
      lat: 53.3090,
      lon: -6.4414,
      filter: "Manned",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark102: {
      name: "Cork Airport",
      lat: 51.8491,
      lon: -8.4899,
      filter: "Manned",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark103: {
      name: "Dublin Airport",
      lat: 53.4264,
      lon: -6.2499,
      filter: "Manned",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark104: {
      name: "Knock Airport",
      lat: 53.7901,
      lon: -8.9215,
      filter: "Manned",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark105: {
      name: "Shannon Airport",
      lat: 52.6997,
      lon: -8.9147,
      filter: "Manned",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      userId: "->users.bernard",
      categoryId: "->categories.category1",
    },
    placemark106: {
      name: "Galway",
      lat: 53.274365,
      lon: -9.052148,
      desc: "I visted Galway in 2010, what a lovely time I had, did you know the Population is 72,729",
      filter: "2010",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark107: {
      name: "Mullingar",
      lat: 53.524763,
      lon: -7.336221,
      desc: "I visted Mullingar in 2012, what a lovely time I had, did you know the Population is 18,416",
      filter: "2012",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark108: {
      name: "Dungarvan",
      lat: 52.92654,
      lon: -7.625041,
      desc: "I visted Dungarvan in 2014, what a lovely time I had, did you know the Population is 8,362",
      filter: "2014",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark109: {
      name: "Youghal",
      lat: 51.953319,
      lon: -7.850468,
      desc: "I visted Youghal in 2016, what a lovely time I had, did you know the Population is 6,785",
      filter: "2016",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark110: {
      name: "Bray",
      lat: 53.205791,
      lon: -6.108928,
      desc: "I visted Bray in 2010, what a lovely time I had, did you know the Population is 31,901",
      filter: "2010",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark111: {
      name: "Sligo",
      lat: 54.270803,
      lon: -8.471503,
      desc: "I visted Sligo in 2012, what a lovely time I had, did you know the Population is 19,402",
      filter: "2012",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark112: {
      name: "Clondalkin",
      lat: 53.322686,
      lon: -6.394744,
      desc: "I visted Clondalkin in 2014, what a lovely time I had, did you know the Population is 43,879",
      filter: "2014",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark113: {
      name: "Gorey",
      lat: 52.67416,
      lon: -6.292949,
      desc: "I visted Gorey in 2016, what a lovely time I had, did you know the Population is 7,193",
      filter: "2016",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark114: {
      name: "Wicklow",
      lat: 52.979121,
      lon: -6.041501,
      desc: "I visted Wicklow in 2010, what a lovely time I had, did you know the Population is 10,070",
      filter: "2010",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark115: {
      name: "Carlow",
      lat: 53.836692,
      lon: -6.924398,
      desc: "I visted Carlow in 2012, what a lovely time I had, did you know the Population is 20,724",
      filter: "2012",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark116: {
      name: "Stillorgan",
      lat: 53.289452,
      lon: -6.200595,
      desc: "I visted Stillorgan in 2014, what a lovely time I had, did you know the Population is 16,018",
      filter: "2014",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark117: {
      name: "Westport",
      lat: 53.801072,
      lon: -9.5225,
      desc: "I visted Westport in 2016, what a lovely time I had, did you know the Population is 5,475",
      filter: "2016",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
    placemark118: {
      name: "Bandon",
      lat: 51.749174,
      lon: -8.736756,
      desc: "I visted Bandon in 2018, what a lovely time I had, did you know the Population is 5,822",
      filter: "2018",
      userId: "->users.bernard",
      categoryId: "->categories.category2",
    },
  },
};
